server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.spring.project.Entity

logging:
  level:
    com.spring.project.Dao: debug

spring:
  datasource:
    url: jdbc:mysql://122.51.57.205:3306/robot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: chenyu
    password: 123456
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  servlet:
   multipart:
     enabled: true
     max-file-size: 30MB
     max-request-size: 100MB